# Generated by Django 3.0.2 on 2020-01-14 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0002_auto_20200114_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardMember',
            new_name='BoardInvite',
        ),
    ]
