# Generated by Django 3.0.2 on 2020-01-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20200114_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinvite',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
