# Generated by Django 3.0.2 on 2020-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20200115_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinvite',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
