# Generated by Django 3.0.2 on 2020-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_boardinvite_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
