# Generated by Django 3.0.2 on 2020-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_auto_20200116_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
