# Generated by Django 3.0.2 on 2020-01-16 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_auto_20200116_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinvite',
            old_name='disable',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='boardmember',
            old_name='disable',
            new_name='archive',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='member_email',
        ),
        migrations.AddField(
            model_name='board',
            name='tokens',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
