# Generated by Django 3.0.2 on 2020-01-16 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_auto_20200116_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tokens',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
