# Generated by Django 3.0.2 on 2020-01-16 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_auto_20200116_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='boardinvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
