# Generated by Django 3.0.2 on 2020-01-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_auto_20200116_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinvite',
            name='owner',
        ),
    ]
