# Generated by Django 3.0.2 on 2020-01-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_remove_boardinvite_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinvite',
            name='activation',
        ),
    ]
