# Generated by Django 3.0.2 on 2020-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_remove_boardinvite_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
