# Generated by Django 3.0.2 on 2020-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_auto_20200131_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
